{% set version = "1.7" %}

package:
  name: toposort
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/t/toposort/toposort-{{ version }}.tar.gz
  sha256: ddc2182c42912a440511bd7ff5d3e6a1cabc3accbc674a3258c8c41cbfbb2125

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3

test:
  imports:
    - toposort
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://bitbucket.org/ericvsmith/toposort
  license: Apache-2.0
  license_file: LICENSE.txt
  license_family: APACHE
  summary: Implements a topological sort algorithm

extra:
  recipe-maintainers:
    - bgruening
    - jakirkham
    - johanneskoester
    - ocefpaf
