{% set name = "toposort" %}
{% set version = "1.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/toposort-{{ version }}.tar.gz
  sha256: bfbb479c53d0a696ea7402601f4e693c97b0367837c8898bc6471adfca37a6bd

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8

test:
  imports:
    - toposort
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://gitlab.com/ericvsmith/toposort
  license: Apache-2.0
  license_file: LICENSE.txt
  license_family: APACHE
  summary: Implements a topological sort algorithm

extra:
  recipe-maintainers:
    - bgruening
    - jakirkham
    - johanneskoester
    - ocefpaf
    - dlaehnemann
