{% set version = "1.9" %}

package:
  name: toposort
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/t/toposort/toposort-{{ version }}.tar.gz
  sha256: f41a34490d44934b533a7bdaff979ee8a47203fd2d8a746db83f2d5ab12458b9

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8

test:
  imports:
    - toposort
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://bitbucket.org/ericvsmith/toposort
  license: Apache-2.0
  license_file: LICENSE.txt
  license_family: APACHE
  summary: Implements a topological sort algorithm

extra:
  recipe-maintainers:
    - bgruening
    - jakirkham
    - johanneskoester
    - ocefpaf
