travis:
  secure:
    BINSTAR_TOKEN: o1/B6qMiKdTerHXyrH2TEN/NOAGnAUSeBn9TbWWx9pdlUiYIY3QeC8Rc8Qycff6mzDRCHMkZkMxPaadz4f0T0qN0Tdl4bt3huZAW5OjJxXFPGbAtbg9BqpokcrzZ/n8wg8Lk0Zf2ibn0VfirYpKihci+MfZtaA1F++y0kvTpSJvXn5433gsXMCXbx6acvKQ+yZtwKxxLuvhwiPZlXSQrVMlDMHg8nf5eK494XB37PEU1dCkGD7tBV0Lnbcbo8tAplZ07fdu7EOn1MR09nCqlkVmuP+YBf9uXVCGAjs4Utw0B6WbR0VHGUNwydkDhqcQjdLn5N8KQd9kmh+mTFSbuO9Uornx50HzJZXLhMROgX1hD4OTe32ZvA+XnspivqldT4zo7W+xkPIyAhHc1EcPsIoHziBOhy+I09zjZygac1frk5HtpZf0Db5eMnYUZ98kykb9EuHsTyHRZFWT27B9JNnNl3J7RdYJh+q3F3J0N1LkerwUitF09PZE4JmAi/ny+TW2aSyXrsBoCFAshI/RvHdch8ggeSU4A4aURLpN8JX1goxvxOYtqLtUrJKeHzL24O6Q9PyJaZLkVazDVyskprFFGjpfrQcIf43npYHF9BT4utxkhmPPZuNURtCMAwqNqPmPLB8eh8j5Gq1MTd9trFiXkOWVK6WZ/dwYPg4fIGtw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
