travis:
  secure:
    BINSTAR_TOKEN: g2hS4/tSi4sKblTHSlUc7eZGO3n3yQXVPxJ98w97A8yhHGybAXfeS9DJI6Vo21l1kv6Je+9jJt6vmy1Xj9bTGMtEvvqCw94Htp3nOBkcICO9+xoDHyMdyEoXv3U+SckQ2nePUskw+KmjZWk/xNseGIprlKLBQpu6Pq5rNA1wyt65HJBj9LZ2fIN+2u5NsGlMEaXl2FuOKVpPHRL5QOLN0stNFbgIWRxJctoz/lfreOpU5XsQbbixc4bzxcX8IevP5Q1E+BQi0S52umSZpRrFmnhqpEUc9LOrPIg+VEers8HuWQxJuCiLjeLavPfztgsVrTvJtPmDQj32HfcbJX7U9ZsEJSMnPYgjowSB0uHXhCUV8J0l2tuqCJ/Pr0XraqFwJJcwurYQtug2D4rTo+/QScee+07ZVXrd6zSokjaELMukOLu2ZSbD1wvy/wmT4BqdIyQZ1tfG1SE9uUHO5m+h4N2+FTDeaoUMNRfzFQDyhz9fMErywnFPVOAgo53y1PnXfyx9HPvvQXGowB7mXxOfyb7qP0FCz0PT5TFpfb4GP0/Ilsg9qSw0VDWdK/upCUU6IBld0pnvob7VjHhftxbnA23z5iuiTHn/21EIx8i46FuFccuDxIjqXHkrw2pqHn2uPG4FWH+pSAxhfPENRdmEPnfS+QWoiX5uY6gjjbumoyI=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
