travis:
  secure:
    BINSTAR_TOKEN: NUsHclp6N3BA/+uKyRJ5Vmc39hG842GpToVzH23qMg6fPITDUaOGLQoWOTMncIgrkkFGjiqACat1CiNRda4b1QD52QFXyEN7hkO6Is0K10HdmhWGunhxfD4EwaIqlgrRFUWXlLyKzHgZtYJr8y+Gk15CPfJ0h0lXpQ/pAUaDyRpXUVBcpaEx6Cns1kS9hfvT7XXkh2NHj+Jr2h7sVlRZh54CXTn+cGKk74Q/pexYoQAntVTfgqBiVe6/ad3RJTxEN6YV6/3i4Mopem7Sjj7ZguCTHgKr3TceEHRFNl5jy8iWH6Pi4Ffn1CcA5v8TxomxCCNgZbUIeC/DoCHbKzxlD+xPKmsrsXAoOzopV2rEkY9qJ2PwIXXaWVoZWf2vG867sFvpw50XAh8QPy2+k45vDb3q7ckUHNiCBqTR3gkhcqu5bQJiMCNgy+a4yM0zqGFoFOjc0NdAE50WmdHs49aAa3ivr++k+NmPh/bL7RvanxqWd48dsHmZM0s4Fi1opATvW33cUCsZrYxed6vFpvRc4hILeXDn7IduX8Qtkf0Iu/JcHaIHjyfpJlYr/LmlhALEBnHz49CxWPnMeDFuzvr1jnvy0gLyo31RSYb4BJWbgUg6/lhYFe0dQ2x9WixNwIjBiYu4lKrgi9C5S+OVBsodALAo8RguDEQXhMQ55ZqnjZE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
